# Generated by Django 6.0.6 on 2026-08-02 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "preferred_city",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "intent",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Buy", "Buy"),
                            ("Rent", "Rent"),
                            ("Invest", "Invest"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "preferred_bhk",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preference",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
