# Generated by Django 6.0.6 on 2026-08-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userpreference"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="created_at",
        ),
        migrations.AddField(
            model_name="userpreference",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="preferred_bhk",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="userpreference",
            name="preferred_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
