# Generated by Django 6.0.6 on 2026-08-02 08:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("properties", "0002_alter_property_city_alter_property_facing_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestmentListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_class",
                    models.CharField(
                        choices=[
                            ("Commercial Office", "Commercial Office"),
                            ("Warehousing", "Warehousing"),
                            ("Pre-Launch Residential", "Pre-Launch Residential"),
                            ("Retail", "Retail"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "expected_roi_percentage",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Expected annual ROI as a percentage, e.g. 12.50 means 12.5%",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "projected_rental_yield",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Projected rental yield as a percentage",
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_investment_amount",
                    models.PositiveIntegerField(
                        help_text="Minimum ticket size in INR (integer rupees, not formatted string)"
                    ),
                ),
                (
                    "lock_in_period_min_months",
                    models.PositiveIntegerField(
                        help_text="Minimum lock-in period in months"
                    ),
                ),
                (
                    "lock_in_period_max_months",
                    models.PositiveIntegerField(
                        help_text="Maximum lock-in period in months (same as min for fixed periods)"
                    ),
                ),
                ("is_pre_launch", models.BooleanField(default=False)),
                (
                    "early_access_ends_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Datetime when early-access / pre-launch window closes. Drives countdown timer.",
                        null=True,
                    ),
                ),
                (
                    "payout_frequency",
                    models.CharField(
                        choices=[("Monthly", "Monthly"), ("Quarterly", "Quarterly")],
                        default="Quarterly",
                        max_length=20,
                    ),
                ),
                (
                    "total_fractional_units",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Reserved for future fractional ownership logic — not used in any transaction flow yet.",
                        null=True,
                    ),
                ),
                (
                    "disclaimer_text",
                    models.TextField(
                        help_text="Regulatory disclaimer REQUIRED on every listing. Must not be blank. Example: 'Projected returns are illustrative estimates, not guaranteed. Past performance is not indicative of future results.'"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investment_listings",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvestmentInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("investor_name", models.CharField(max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                (
                    "preferred_investment_range",
                    models.CharField(
                        choices=[
                            ("10L-25L", "₹10L – ₹25L"),
                            ("25L-50L", "₹25L – ₹50L"),
                            ("50L-1Cr", "₹50L – ₹1Cr"),
                            ("1Cr+", "₹1Cr+"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "pan_number",
                    models.CharField(
                        blank=True,
                        help_text="Collecting early for future KYC; nullable now.",
                        max_length=10,
                        null=True,
                    ),
                ),
                ("requested_pitch_deck", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("converted", "Converted"),
                            ("dropped", "Dropped"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="investment_inquiries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "investment_listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inquiries",
                        to="investments.investmentlisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
