# Generated by Django 6.0.6 on 2026-08-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="investmentlisting",
            name="is_sample_data",
            field=models.BooleanField(
                default=True,
                help_text="Flags listing as illustrative pilot sample data. Displays 'Sample Data' badge.",
            ),
        ),
    ]
