# Generated by Django 6.0.6 on 2026-08-01 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("rented", "Rented"),
                            ("sold", "Sold"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("images", models.JSONField(blank=True, default=list)),
                (
                    "city",
                    models.CharField(
                        choices=[
                            ("Ahmedabad", "Ahmedabad"),
                            ("Bangalore", "Bangalore"),
                            ("Delhi NCR", "Delhi NCR"),
                            ("Hyderabad", "Hyderabad"),
                            ("Mumbai", "Mumbai"),
                        ],
                        default="Ahmedabad",
                        max_length=100,
                    ),
                ),
                (
                    "sub_market",
                    models.CharField(blank=True, default="Central", max_length=100),
                ),
                ("locality", models.CharField(default="Bodakdev", max_length=100)),
                (
                    "property_type",
                    models.CharField(
                        choices=[
                            ("Apartment", "Apartment"),
                            ("Villa", "Villa"),
                            ("Independent House", "Independent House"),
                            ("Penthouse", "Penthouse"),
                            ("Studio", "Studio"),
                        ],
                        default="Apartment",
                        max_length=50,
                    ),
                ),
                ("bhk", models.IntegerField(default=2)),
                ("area_sqft", models.FloatField(default=1200.0)),
                ("floor", models.IntegerField(default=2)),
                ("total_floors", models.IntegerField(default=10)),
                ("age_years", models.IntegerField(default=3)),
                (
                    "furnishing",
                    models.CharField(
                        choices=[
                            ("Unfurnished", "Unfurnished"),
                            ("Semi-Furnished", "Semi-Furnished"),
                            ("Fully Furnished", "Fully Furnished"),
                        ],
                        default="Semi-Furnished",
                        max_length=50,
                    ),
                ),
                (
                    "facing",
                    models.CharField(
                        choices=[
                            ("East", "East"),
                            ("West", "West"),
                            ("North", "North"),
                            ("South", "South"),
                            ("North-East", "North-East"),
                            ("North-West", "North-West"),
                            ("South-East", "South-East"),
                            ("South-West", "South-West"),
                        ],
                        default="East",
                        max_length=50,
                    ),
                ),
                ("dist_metro_km", models.FloatField(default=1.5)),
                ("dist_school_km", models.FloatField(default=1.0)),
                ("dist_hospital_km", models.FloatField(default=1.5)),
                ("dist_it_hub_km", models.FloatField(default=3.0)),
                ("has_gym", models.BooleanField(default=False)),
                ("has_pool", models.BooleanField(default=False)),
                ("has_clubhouse", models.BooleanField(default=False)),
                ("has_security", models.BooleanField(default=True)),
                ("has_power_backup", models.BooleanField(default=True)),
                ("has_parking", models.BooleanField(default=True)),
                ("has_lift", models.BooleanField(default=True)),
                ("rera_approved", models.BooleanField(default=True)),
                ("listed_price", models.FloatField(default=5000000.0)),
                ("predicted_price", models.FloatField(blank=True, null=True)),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("based_on", models.CharField(blank=True, max_length=100, null=True)),
                ("deal_tag", models.CharField(blank=True, max_length=50, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
