# Generated by Django 6.0.6 on 2026-08-01 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="city",
            field=models.CharField(
                choices=[
                    ("Delhi NCR", "Delhi NCR"),
                    ("Mumbai", "Mumbai"),
                    ("Bangalore", "Bangalore"),
                    ("Hyderabad", "Hyderabad"),
                    ("Ahmedabad", "Ahmedabad"),
                ],
                default="Ahmedabad",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="facing",
            field=models.CharField(
                choices=[
                    ("North", "North"),
                    ("South", "South"),
                    ("East", "East"),
                    ("West", "West"),
                    ("North-East", "North-East"),
                    ("North-West", "North-West"),
                    ("South-East", "South-East"),
                    ("South-West", "South-West"),
                ],
                default="East",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="furnishing",
            field=models.CharField(
                choices=[
                    ("Unfurnished", "Unfurnished"),
                    ("Semi-Furnished", "Semi-Furnished"),
                    ("Fully-Furnished", "Fully-Furnished"),
                    ("Fully Furnished", "Fully Furnished"),
                ],
                default="Semi-Furnished",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("Apartment", "Apartment"),
                    ("Independent House", "Independent House"),
                    ("Villa", "Villa"),
                    ("Penthouse", "Penthouse"),
                    ("Studio", "Studio"),
                ],
                default="Apartment",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="status",
            field=models.CharField(
                choices=[
                    ("for_sale", "For Sale"),
                    ("for_rent", "For Rent"),
                    ("available", "Available"),
                    ("sold", "Sold"),
                    ("rented", "Rented"),
                ],
                default="for_sale",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.CharField(max_length=500)),
                ("is_primary", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="properties.property",
                    ),
                ),
            ],
        ),
    ]
