# Generated by Django 6.0.6 on 2026-08-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_alter_property_city_alter_property_facing_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
