# Generated by Django 6.0.6 on 2026-08-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "properties",
            "0004_alter_property_latitude_alter_property_longitude_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathroom",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="developer",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="property",
            name="possession_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Ready to Move", "Ready to Move"),
                    ("Under Construction", "Under Construction"),
                    ("Unknown", "Unknown"),
                ],
                default="Ready to Move",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="project_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="facing",
            field=models.CharField(
                choices=[
                    ("North", "North"),
                    ("South", "South"),
                    ("East", "East"),
                    ("West", "West"),
                    ("North-East", "North-East"),
                    ("North-West", "North-West"),
                    ("South-East", "South-East"),
                    ("South-West", "South-West"),
                    ("Unknown", "Unknown"),
                ],
                default="East",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="furnishing",
            field=models.CharField(
                choices=[
                    ("Unfurnished", "Unfurnished"),
                    ("Semi-Furnished", "Semi-Furnished"),
                    ("Fully-Furnished", "Fully-Furnished"),
                    ("Fully Furnished", "Fully Furnished"),
                    ("Unknown", "Unknown"),
                ],
                default="Semi-Furnished",
                max_length=50,
            ),
        ),
    ]
