# Generated by Django 6.0.6 on 2026-08-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_property_bathroom_property_developer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="external_source_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=100, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="dist_hospital_km",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="dist_it_hub_km",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="dist_metro_km",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name="property",
            name="dist_school_km",
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
