# Generated by Django 6.0.6 on 2026-08-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_property_external_source_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LocalityCoordinateCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(max_length=100)),
                ("locality", models.CharField(max_length=100)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("geocoded_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(default="nominatim", max_length=50)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["city", "locality"], name="loc_coord_cache_idx"
                    )
                ],
                "unique_together": {("city", "locality")},
            },
        ),
    ]
