# Generated by Django 6.0.6 on 2026-08-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_inquiry_agent_alter_inquiry_status_lead_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadinteraction",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="leadinteraction",
            name="agent",
        ),
        migrations.RemoveField(
            model_name="inquiry",
            name="agent",
        ),
        migrations.AlterField(
            model_name="inquiry",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "New"),
                    ("contacted", "Contacted"),
                    ("closed", "Closed"),
                ],
                default="new",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Lead",
        ),
        migrations.DeleteModel(
            name="LeadInteraction",
        ),
    ]
