# Generated by Django 6.0.6 on 2026-08-01 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaseagreement",
            name="rent_amount",
            field=models.FloatField(default=30000.0),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="lease",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="maintenance_requests",
                to="management_app.leaseagreement",
            ),
        ),
        migrations.AddField(
            model_name="maintenancerequest",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaseagreement",
            name="monthly_rent",
            field=models.FloatField(default=30000.0),
        ),
        migrations.AlterField(
            model_name="leaseagreement",
            name="security_deposit",
            field=models.FloatField(default=90000.0),
        ),
        migrations.AlterField(
            model_name="maintenancerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("pending", "Pending"),
                    ("in_progress", "In Progress"),
                    ("resolved", "Resolved"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("due_date", models.DateField()),
                ("paid_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("late", "Late"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lease",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="management_app.leaseagreement",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
    ]
